# Workflow для вызова кастомных экшенов
#- Первый Использует пеерданный параметр для присвоения переменной
#- Второй создает Issue при падении pull в ветку develop (дублирует существующий шаг )
name: CUSTOM ACTIONS
on:
  pull_request:
    branches:
      - develop
jobs:
  send-slack-msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: add_actions_in_docker # test brunch

      - name: Send Slack Message via Docker
        uses: ./.github/actions/slack
        with:
          slack_webhook: ${{secrets.SLACK_WEBHOOK}}
          message: Hello slack from Docker

      - name: Open Issue by custom action # run only if Docker is broken in this pipeline
        if: failure()
        uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: "Automated issue for commit: ${{github.sha}} by Custom action"
          body: "This issue was automatically created by the GitHub Action workflow **${{github.workflow}}**. \n\n The commit hash was: _${{github.sha}}_."
          assignees: "${{github.event.pull_request.user.login}}"

  say-hello-from-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: add_actions_in_docker # test brunch
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{steps.hello.outputs.time}}"
          echo $HELLO
