name: Notify on Issue
on:
  issues:
    types: [opened]
jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: '{"text":"New issue created: <${{github.event.issue.html_url}}|${{github.event.issue.title}}.>"}'
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK}}
