# При PR в ветку:
#- установить зависимости
#- использовать кеш
#- прогнать линтер и поправить код
#- прогнать тесты
#- прогнать покрытие кода
#- сохранить отчет по покрытию

name: PR to Develop branch
on:
  pull_request:
    branches: [develop]
jobs:
  pr-to-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: npm ci
      - name: Start Linter
        run: npm run format:check
      - name: Run Coverage
        run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
      - name: Open Issue
        if: failure()
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{github.repository}}/issues \
          --header 'Authorization: Bearer ${{secrets.CUSTOM_TOKEN}}' \
          --header "Accept: application/vnd.github.v3+json" \
          --header 'Content-type: application/json' \
          -d '{"title":"Automated issue for commit: ${{github.sha}}", \
          "body":"This issue was automatically createdby the GitHub Action workflow **${{github.workflow}}**. \n\n The commit hash was: _${{github.sha}}_.", \
          "assignees":["${{github.event.pull_request.user.login}}"]}'
