# При PR в ветку:
#- установить зависимости
#- использовать кеш
#- прогнать линтер и поправить код
#- прогнать тесты
#- прогнать покрытие кода
#- сохранить отчет по покрытию

#При падении:
#- создать Issue
#- уведомить в slack

name: PR to Develop branch
on:
  pull_request:
    branches: [develop]
jobs:
  pr-to-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: npm ci
      - name: Start Linter
        run: npm run format:check
      - name: Run Coverage
        run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
      - name: Open Issue by 3rd party action
        if: failure()
        uses: rishabhgupta/git-action-issue@v2
        with:
          token: ${{secrets.CUSTOM_TOKEN}}
          title: "Automated issue for commit: ${{github.sha}} by 3rd party action"
          body: "This issue was automatically created by the GitHub Action workflow **${{github.workflow}}**. \n\n The commit hash was: _${{github.sha}}_."
          assignees: "${{github.event.pull_request.user.login}}"
